### PR TITLE
Update .ftl files from L10n repo

### PR DESCRIPTION
**Pull request by alexgibson**
Third time is a charm?

### CODE REVIEW

**Review by pmac — APPROVED** [review]
JSON files look great. I'll defer to @Pike for the .ftl.

**Review by Pike — COMMENTED** [review]
This should also update the configs?

I did some checks on content and metadata, that looks OK.

We agreed to not remove files for now, right? I guess I should do an independent PR to remove the empty `mission.ftl` files that we have lying around still.

**Comment by alexgibson** [comment]
> This should also update the configs?

As far as I understand, this repo is concerned only with updating the list of active locales, right @pmac?

I'll defer to Paul on what to do with empty files.

**Comment by pmac** [comment]
> This should also update the configs?

I didn't see a point in keeping the configs in this repo. My understanding was that the canonical configs would live in bedrock, and that automation would update the l10n repo with those config changes. We still have that automation to do.

> We agreed to not remove files for now, right? I guess I should do an independent PR to remove the empty `mission.ftl` files that we have lying around still.

I could code this such that files removed from your repo results in them being removed from ours, but it doesn't work like that right now. Doing a separate manual PR to remove some things is fine. Let me know if this automation doing file removal is something we want.

**Comment by Pike** [comment]
So, the configs are in the mozmeao repo, and I tried to run some verifications with compare-locales, and didn't get the expected results 'cause the configs were out of date.

I would stay away from automatically removing content for now, as long as we're not 100% confident in all the bits and pieces.

**Comment by alexgibson** [comment]
Is there anything else that needs doing here, or prevents this from merging?

**Comment by pmac** [comment]
Not as far as I'm concerned. I can update the script to include updating the configs, but I don't think that's required before merging this.

**Comment by alexgibson** [comment]
Closing this so we can try again once https://github.com/mozilla/bedrock/pull/8557 has been reviewed 👍

**Pull request closed without merging**
