### PR TITLE
Pull latest changes from upstream

### PR DESCRIPTION
**Pull request by alexgibson**

### CODE REVIEW

**Comment by alexgibson** [comment]
@pmac r?

**Comment by alexgibson** [comment]
Main thing to review here is probably the changes in `/metadata`. the rest is just copy/paste from the L10n repo.

**Comment by Pike** [comment]
So there's a bug in `mission.ftl` migration that's sneaking into prod here.

I'd like to take a day or two to investigate that more, and possibly change the data in the `mozilla-l10n/www-l10n` repo.

Basically, we're adding a ton of English strings to migrated files, which we shouldn't. The bug is probably in `fluent.migrate` itself, so I'll need to see if that's the case, and how that propagates.

We only took activations of `mission` from the upstream `.lang` tags for now, right?

**Comment by Pike** [comment]
From a review process POV, would it make sense to keep the ftl updates in separate commits from the metadata updates? May or may not make it easier to digest what's going. It may make it easier to understand what, but maybe not why?

Really more of a question.

**Comment by alexgibson** [comment]
I'm going to close this and we can re-approach & discuss when we think the migration bugs are fixed 👍

**Pull request closed without merging**
