### PR TITLE
Update .ftl files from l10n-team repo

### PR DESCRIPTION
**Pull request by alexgibson**
This time with config files

### CODE REVIEW

**Comment by pmac** [comment]
@Pike TOML files are included now. Do your tools work better now?

**Comment by Pike** [comment]
This looks good to me.

Do you want to update this for https://github.com/mozilla-l10n/www-l10n/commit/db015f2d7dc816baaf28f29bf0d65b2af89d8c85, too?

**Comment by alexgibson** [comment]
I’d like to merge this, and and we can follow up with updates that have happened since this opened. Ideally, I’d like to see if we can set up with automating further updates using a web hook.

**Comment by pmac** [comment]
That is the next step for sure

**Pull request merged**
